services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
      - ./.docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env.mongodb
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env.backend
    depends_on:
      - mongodb
    restart: always

  front:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        BASE_API_URL: ${BASE_API_URL}
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data: